### ISSUE TITLE
model based on coco

### ISSUE THREAD

**Issue by mouad47** [kutoniea/YOLOv3-Object-Detection-VOC2012#1]
hello @kutoniea 
I was around looking for a pretraind yolov3 model based on VOC ,I think the the darknet model that's you tried based on COCO dataset, coz yolov3 doesn't support voc anymore
thank you

**Comment by kutoniea** [comment]
@mouad47 Thanks for updating. I am also aware Yolo is undergoing some changes recently because of the new version author and thus different programming content is followed. 
There are still different pre-trained weights you can use to replace the original one. You can find more information here. https://github.com/leggedrobotics/darknet_ros/issues/90
